experiment_name: "FeedForward_absolute_20AC_Actlrx10"
environment:
  class_path: atcenv.src.environment_objects.environment.DefaultEnvironment
  init_args:
    render_frequency: 0
model:
  class_path: atcenv.src.models.sac.SAC
  init_args:
    action_dim: 2
    alpha_lr: 3e-4
    actor_lr: 3e-4
    critic_q_lr: 3e-3
    critic_v_lr: 3e-3
    gamma: 1.0
    tau: 5e-3
    policy_update_freq: 8
    initial_random_steps: 0
    buffer:
      class_path: atcenv.src.models.replay_buffer.ReplayBuffer
      init_args:
        obs_dim: 18
        action_dim: 2
        n_agents: 20
        size: 20000000
        batch_size: 2048
    actor:
      class_path: atcenv.src.models.actor.FeedForwardActor
      init_args:
        in_dim: 18
        out_dim: 2
    critic_q_1:
      class_path: atcenv.src.models.critic_q.FeedForward_Q
      init_args:
        state_dim: 18
        action_dim: 2
    critic_q_2:
      class_path: atcenv.src.models.critic_q.FeedForward_Q
      init_args:
        state_dim: 18
        action_dim: 2
    critic_v:
      class_path: atcenv.src.models.critic_v.FeedForward_V
      init_args:
        in_dim: 18
    critic_v_target:
      class_path: atcenv.src.models.critic_v.FeedForward_V
      init_args:
        in_dim: 18
scenario:
  num_episodes: 10000
  num_flights: 20
  airspace_area: 10000000000
  traffic_density: 0
  test_scenario_dir: "hello"
  num_test_episodes: 0
  test_frequency: 0
airspace:
  class_path: atcenv.src.environment_objects.airspace.EnrouteAirspace
aircraft:
  min_speed: 200
  max_speed: 250
  min_distance: 10000
observation:
  class_path: atcenv.src.observation.observation.BasicAbs
  init_args:
    observation_size: 18
    num_ac_state: 3
    normalize_data: True
    create_normalization_data: False
    normalization_data_file: "basic_abs_normalization.p"
    normalization_samples: 500000
reward:
  class_path: atcenv.src.reward.reward.DefaultReward
  init_args:
    intrusion_weight: -1
    drift_weight: -0.1
logger:
  class_path: atcenv.src.logger.logger.RLLogger
  init_args:
    log_frequency: 100
    verbose: True
