experiment_name: "LOFI-SAC-100"
environment:
  class_path: CR_LoFi.atcenv.src.environment_objects.environment.DefaultEnvironment
  init_args:
    render_frequency: 0
model:
  class_path: CR_LoFi.atcenv.src.models.sac.SAC
  init_args:
    action_dim: 2
    alpha_lr: 3e-4
    actor_lr: 3e-4
    critic_q_lr: 3e-3
    critic_v_lr: 3e-3
    gamma: 1.0
    tau: 5e-3
    policy_update_freq: 8
    initial_random_steps: 0
    buffer:
      class_path: CR_LoFi.atcenv.src.models.replay_buffer.ReplayBuffer
      init_args:
        obs_dim: 31
        action_dim: 2
        n_agents: 2
        size: 20000000
        batch_size: 2048
    actor:
      class_path: CR_LoFi.atcenv.src.models.actor.FeedForwardActor
      init_args:
        in_dim: 31
        out_dim: 2
    critic_q_1:
      class_path: CR_LoFi.atcenv.src.models.critic_q.FeedForward_Q
      init_args:
        state_dim: 31
        action_dim: 2
    critic_q_2:
      class_path: CR_LoFi.atcenv.src.models.critic_q.FeedForward_Q
      init_args:
        state_dim: 31
        action_dim: 2
    critic_v:
      class_path: CR_LoFi.atcenv.src.models.critic_v.FeedForward_V
      init_args:
        in_dim: 31
    critic_v_target:
      class_path: CR_LoFi.atcenv.src.models.critic_v.FeedForward_V
      init_args:
        in_dim: 31
scenario:
  num_episodes: 200
  num_agents: 1
  num_flights: 0
  num_ac_state: 4
  airspace_area: [2400, 3750]
  traffic_density: [0.005, 0.001]
  test_scenario_dir: "hello"
  num_test_episodes: 0
  test_frequency: 0
airspace:
  class_path: CR_LoFi.atcenv.src.environment_objects.airspace.EnrouteAirspace
aircraft:
  min_speed: 200
  max_speed: 250
  min_distance: 9260
observation:
  class_path: CR_LoFi.atcenv.src.observation.observation.Local
  init_args:
    observation_size: 31
    num_ac_state: 4
    normalize_data: True
    create_normalization_data: False
    normalization_data_file: "local_normalization.p"
    normalization_samples: 1000
reward:
  class_path: CR_LoFi.atcenv.src.reward.reward.DefaultReward
  init_args:
    intrusion_weight: -1
    drift_weight: -0.1
logger:
  class_path: CR_LoFi.atcenv.src.logger.logger.RLLogger
  init_args:
    log_frequency: 25
    verbose: True
baseline: False