experiment_name: "norm"
environment:
  class_path: CR_LoFi.atcenv.src.environment_objects.environment.DefaultEnvironment
  init_args:
    render_frequency: 0
model:
  class_path: CR_LoFi.atcenv.src.models.model.Random
  init_args:
    action_dim: 2
scenario:
  num_episodes: 1000
  num_agents: 1
  num_flights: 0
  num_ac_state: 4
  airspace_area: [2400, 3750]
  traffic_density: [0.003, 0.007]
  test_scenario_dir: "hello"
  num_test_episodes: 0
  test_frequency: 0
airspace:
  class_path: CR_LoFi.atcenv.src.environment_objects.airspace.EnrouteAirspace
aircraft:
  min_speed: 200
  max_speed: 250
  min_distance: 10000
observation:
  class_path: CR_LoFi.atcenv.src.observation.observation.Local
  init_args:
    observation_size: 31
    num_ac_state: 4
    normalize_data: False
    create_normalization_data: True
    normalization_data_file: "local_normalization.p"
    normalization_samples: 50000
reward:
  class_path: CR_LoFi.atcenv.src.reward.reward.DefaultReward
logger:
  class_path: CR_LoFi.atcenv.src.logger.logger.RLLogger
  init_args:
    log_frequency: 0
    verbose: True
