experiment_name: "MVP_straight_look1000"
environment:
  class_path: atcenv.src.environment_objects.environment.DefaultEnvironment
  init_args:
    render_frequency: 1
model:
  class_path: atcenv.src.models.model.MVP
  init_args:
    action_dim: 2
    t_lookahead: 1000
scenario:
  num_episodes: 20000
  num_flights: 10
  airspace_area: 10000000000
  traffic_density: 0
  test_scenario_dir: "hello"
  num_test_episodes: 0
  test_frequency: 0
  random_seed: 3
airspace:
  class_path: atcenv.src.environment_objects.airspace.EnrouteAirspace
aircraft:
  min_speed: 200
  max_speed: 250
  min_distance: 10000
observation:
  class_path: atcenv.src.observation.observation.StateBasedMVP
  init_args:
    observation_size: 10
    normalize_data: True
    create_normalization_data: False
    normalization_data_file: "local_normalization.p"
    normalization_samples: 500000
reward:
  class_path: atcenv.src.reward.reward.DefaultReward
  init_args:
    intrusion_weight: -1
    drift_weight: -0.1
logger:
  class_path: atcenv.src.logger.logger.BasicLogger
  init_args:
    log_frequency: 0
    verbose: True
